### ISSUE TITLE
What is MNTP trained lora weights?

### ISSUE THREAD

**Issue by ganeshkrishnan1** [McGill-NLP/llm2vec#1]
How can we get those weights from a standard LLM?

Eg mixtral 8x7b base model

**Comment by vaibhavad** [comment]
we have trained and uploaded those weights on HuggingFace

[Mistral MNTP](https://huggingface.co/McGill-NLP/LLM2Vec-Mistral-7B-Instruct-v2-mntp)

[Llama MNTP](https://huggingface.co/McGill-NLP/LLM2Vec-Llama-2-7b-chat-hf-mntp)

[Sheared-Llama MNTP](https://huggingface.co/McGill-NLP/LLM2Vec-Sheared-LLaMA-mntp)

Our training code and scripts will be released soon.
