### ISSUE TITLE
Is it a desired behaviour that _encode always returns embeddings on cpu, even though we pass device argument to it?

### ISSUE THREAD

**Issue by VProv** [McGill-NLP/llm2vec#100]
![image](https://github.com/McGill-NLP/llm2vec/assets/22977076/323ee4c1-2854-49ae-bf34-c23cbd78ae31)

**Comment by VProv** [comment]
This behaviour is a bit confusing, maybe at least add a description

**Comment by vaibhavad** [comment]
Hi @VProv, 

Thanks for contributing via #101. Yes, this is the desired behaviour to avoid OOM problems on GPU with large datasets. If you want, you can raise another PR that gives an additional argument to retain the embeddings on GPU. It will be also be helpful to include a warning in such a case as GPU memory will constantly keep on increasing as more documents are encoded.

**Comment by vaibhavad** [comment]
Closing as it is stale. Feel free to re-open if you have any more questions.
