### ISSUE TITLE
prepare_for_tokenization (Instruct template) is used for supervised training but not for inference (example)

### ISSUE THREAD

**Issue by bzantium** [McGill-NLP/llm2vec#103]
Thanks for sharing code! 
I have some question:

- following the [code](https://github.com/McGill-NLP/llm2vec/blob/361f77852dbc87ca0a8cd94d0bdcc24be3abb9ea/llm2vec/llm2vec.py#L133), instruct template is used for training but not used for inference (examples). don't need to use template for inference? 
- I am also curious how you use Instruction (including whether you use template or not) when evaluating on MTEB. If possible, can you share code to evaluate?

**Comment by Gbone3176** [comment]
Hello! I also have some questions about the usage of this function: During the training of mntp and SimCSE, was this function not used to wrap the input? If so, could this affect the output of the instruction fine-tuning model? Additionally, I noticed that the embedding mask does not process the special token introduced by the wrapping. Could this impact the subsequent encoding results? I would greatly appreciate the opportunity to discuss this with you. Thank you!
