### ISSUE TITLE
Instruction for corpus and query on MTEP Evaluation

### ISSUE THREAD

**Issue by bzantium** [McGill-NLP/llm2vec#104]
Do you use same instruction written in the paper for corpus and query on ReRank or Retrieval Benchmark?

**Comment by vaibhavad** [comment]
Hi @bzantium,

Thank you for your interest in our work. The corpus is encoding without any instruction following previous works ([e5-mistal-instruct](https://arxiv.org/abs/2401.00368), [echo-embeddings](https://arxiv.org/abs/2402.15449)).
