### ISSUE TITLE
Some words can not be encoded (upper case and lower case)

### ISSUE THREAD

**Issue by wyhwhy** [McGill-NLP/llm2vec#105]
Hi, @vaibhavad 
I met the same problem as @Yan2266336 raised. For example, when trying to encode the word 'alleged', it returns the following error:
**RuntimeError**: The expanded size of the tensor (2) must match the existing size (3) at non-singleton dimension 0.  Target sizes: [2].  Tensor sizes: [3].
 I am using llm2vec==0.1.8 plus mntp-supervised and could you please check the problem? Thanks!

**Comment by wyhwhy** [comment]
> Hi, @vaibhavad I met the same problem as @Yan2266336 raised. For example, when trying to encode the word 'alleged', it returns the following error: **RuntimeError**: The expanded size of the tensor (2) must match the existing size (3) at non-singleton dimension 0. Target sizes: [2]. Tensor sizes: [3]. I am using llm2vec==0.1.8 plus mntp-supervised and could you please check the problem? Thanks!

Meanwhile, I found that even if the encoding vector of 'Alleged' and 'ALLEGED' is the same, the encoding vector of the following two sentences are different: 'Alleged is related to crime' and 'ALLEGED is related to crime'. Can you explain it?

**Comment by vaibhavad** [comment]
Hi @wyhwhy,

Thank you for your interest in our work. Can you provide a code sample to reproduce the issue?

**Comment by wyhwhy** [comment]
> Hi @wyhwhy,
> 
> Thank you for your interest in our work. Can you provide a code sample to reproduce the issue?
> 
> You can also see my [response](https://github.com/McGill-NLP/llm2vec/issues/80#issuecomment-2187151832) on #80 to see if it is the same underlying problem.

Hi, since this is not the same problem as issue #80, the code sample is as follows:

import torch
from llm2vec import LLM2Vec
l2v = LLM2Vec.from_pretrained(
    "llama3-8B",
    peft_model_name_or_path="/McGill-NLP/LLM2Vec-Meta-Llama-3-8B-Instruct-mntp-supervised",
    device_map="cuda" if torch.cuda.is_available() else "cpu",
    torch_dtype=torch.bfloat16,
)
documents = ['alleged','Alleged','ALLEGED']
d_reps = l2v.encode([documents[0]]) #error happens here
d_reps = l2v.encode([documents[1]]) #no error
d_reps = l2v.encode([documents[2]]) #no error

We have found that this bug comes from **Line 160 in llm2vec.py**, in which the revised code should be: 't = text.split(" !@#$%^&*()")', .i.e., a space in front of '!'. Thanks.

**Comment by vaibhavad** [comment]
Thanks for finding this bug and fixing it!
