### ISSUE TITLE
Run llm2vec model with Ollama/LMStudio

### ISSUE THREAD

**Issue by rodion-m** [McGill-NLP/llm2vec#11]
Is there a way to run llm2vec model with Ollama/LMStudio?

**Comment by vaibhavad** [comment]
Hi, currently llm2vec is not integrated with Ollama/LMStudio.

**Comment by rodion-m** [comment]
Is it possible to convert llm2vec models to a gguf format?

**Comment by vaibhavad** [comment]
I believe it will require more than just naive conversion of weights, as LLM2Vec use bidirectional attention. I will look into gguf conversion in more detail in the future. Feel free to open a pull request if you want to work on this.

**Comment by dukecyto** [comment]
> I believe it will require more than just naive conversion of weights, as LLM2Vec use bidirectional attention

I am checking out llama.cpp and its GGUF converter in an attempt to run Llama3-based LLM2Vec with llama.cpp (not with Ollama/LMStudio as in OP). Do you anticipate that this conversion requires more than setting `self.gguf_writer.add_causal_attention(False)` in `convert_hf_to_gguf.py` to enable bidirectional attention? I got the converter to output Llama3-based LLM2Vec GGUF, but I am not confident if the llama.cpp inference with this GGUF is correct.

**Comment by dukecyto** [comment]
FYI I opened a discussion here https://github.com/ggml-org/llama.cpp/discussions/13368
