### ISSUE TITLE
Test llama and Mistral on mteb benchmark

### ISSUE THREAD

**Issue by NouamaneELGueddarii** [McGill-NLP/llm2vec#111]
Hello, i am trying to test the llama Modela and Mistral on the german clustering benchmark on MTEB, how can i do it ?  
the code base of mteb just changed, the encode function requires a new prompt_name which is not implemented in the llm2vec encode function.

**Comment by vaibhavad** [comment]
I have added the code and documentation to evaluate models on MTEB, you can find it [here](https://github.com/McGill-NLP/llm2vec?tab=readme-ov-file#mteb-evaluation). It is compatible with the latest version of MTEB (which requires a prompt_name in encode)

**Comment by vaibhavad** [comment]
Closing as it is stale. Feel free to re-open if you have any more questions.

**Comment by NouamaneELGueddarii** [comment]
Thank you for your answer. I have tried to use the code you provided, but i seems tehre is an issue with the loading of adapter in PEFT. Here is the error: ImportError: cannot import name 'inject_adapter_in_model' from 'peft' (/opt/conda/lib/python3.11/site-packages/peft/__init__.py). 

Do you also have the same error, or is it an issue on my end? 
Thank you!
