### ISSUE TITLE
Fine Tuning Script for Token Classification

### ISSUE THREAD

**Issue by WorldHellow** [McGill-NLP/llm2vec#112]
Hello, I want to use your work on custom BIO annotation style dataset. I was wondering if you already have custom fine-tuning scripts with classification head on to for token classification. Something similar to [Bi-LLM](https://github.com/WhereIsAI/BiLLM?tab=readme-ov-file#ner).

**Comment by vaibhavad** [comment]
Hi @WorldHellow,

Thanks for your interest in our work, you can check our script for training models for token-level classification [here](https://github.com/McGill-NLP/llm2vec/blob/main/experiments/run_word_task.py).

Let me know if you have any further questions.

**Comment by vaibhavad** [comment]
Closing as it is stale. Feel free to re-open if you have any more questions.
