### ISSUE TITLE
MistralBiModel.forward() got an unexpected keyword argument 'cache_position'

### ISSUE THREAD

**Issue by su-park** [McGill-NLP/llm2vec#119]
Hello,
When I run 'run_mntp.py' with the Mistral model, I receive the following error message:

```
TypeError: MistralBiModel.forward() got an unexpected keyword argument 'cache_position'
```

Llama2 and Gemma operates normally.
Could you please help me?

### Enviroment
---
If possible, please also confirm the versions of the packages you are working with, as it would be helpful.
- python 3.10
- llm2vec==0.2.0
- transformers==4.42.3
- accelerate==0.27.2
- peft==0.8.2

**Comment by vaibhavad** [comment]
Hi @su-park,

Thanks for your interest in our work. As transformers library keeps changing the implementation of causal masking, it is very difficult for us to keep changing our code accordingly. I would recommend using transformers >=4.39.1 and <=4.40.2. For these versions, we have verified that everything is working. I have also updated this requirement in 67dab12

**Comment by su-park** [comment]
Thank you.
It worked when I set the version of transformers == 4.39.1
