### ISSUE TITLE
Building with `pretrained_model` not `instruct_model`?

### ISSUE THREAD

**Issue by su-park** [McGill-NLP/llm2vec#120]
Hello. 
I have one more question.

When building models, You primarily have used `instruct models`, but is it also possible to use `pretrained models`? 
Is there a performance difference when building with `pretrained_model` and `instruct_model` of the same model or any special reasons to prefer `instruct_model`?

**Comment by vaibhavad** [comment]
Hi @su-park,

we used instruct models because the evaluation is done using instructions, hence, instruction models are better suited for the task than the pretrained models of the same model family. We have not yet experimented with using `pretrained_model` and `instruct_model` of the same model.
