### ISSUE TITLE
Test on german clustering 

### ISSUE THREAD

**Issue by NouamaneELGueddarii** [McGill-NLP/llm2vec#124]
I want to the l2v models on german clustering, do i have to train a model from the ground up using MNTP and contrastive learning or i can use the models that are already trained

**Comment by vaibhavad** [comment]
You can use the models that are already trained, however, the performance will probably not be optimal as these models were trained only on English data. For optimal performance, training a model on German data is recommended.

**Comment by vaibhavad** [comment]
Closing as stale. Feel free to re-open if you have any further questions.
