### ISSUE TITLE
Training Code Timeline (estimated release date)

### ISSUE THREAD

**Issue by eek** [McGill-NLP/llm2vec#13]
Do you guys have a timeline when the training code will be available? I think the community is eager to apply it to a ton of different LLMs. Congrats on the work!

**Comment by monilouise** [comment]
I'm also looking forward to the training code! Indeed, it is an outstanding contribution!

**Comment by ParishadBehnam** [comment]
Hi,

Thanks for your interest. We will try to release the code by the end of this week.
