### ISSUE TITLE
Access denied error

### ISSUE THREAD

**Issue by Sreelakshmi-k** [McGill-NLP/llm2vec#130]
I am getting access denied error.
I am using the code sample mentioned din your github.
Kindly help

OSError: You are trying to access a gated repo.
Make sure to have access to it at https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.2.
401 Client Error. (Request ID: Root=1-66a71178-307f6efd0cb726526dab58c4;5159a703-3843-4fbb-81cb-7896ada5c5c3)

Cannot access gated repo for url https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.2/resolve/main/config.json.
Access to model mistralai/Mistral-7B-Instruct-v0.2 is restricted. You must be authenticated to access it.

**Comment by vaibhavad** [comment]
Hi @Sreelakshmi-k,

Thanks for your interest in our work.

You have to request access to Mistral [here](https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.2) and provide huggingface token as an environment variable for the code to run properly.

**Comment by vaibhavad** [comment]
Closing as it is stale. Feel free to re-open if the issue still persists.

**Comment by vaibhavad** [comment]
Closing as it is stale. Feel free to re-open if the issue still persists.
