### ISSUE TITLE
Where is the code for reproducing "bi+mntp+simcse"?

### ISSUE THREAD

**Issue by Sherrylife** [McGill-NLP/llm2vec#143]
It's seems that the scripts in the folder of experiments are only for "bi+mntp" or "bi+simcse", is there any script that I had missed to reproduce "bi+mntp+simcse"?

**Comment by vaibhavad** [comment]
Hi @Sherrylife,

thanks for your interest in our work. The script released is actually for "bi+mntp+simce". In the configuration file, we provide the [peft address to "bi+mntp"](https://github.com/McGill-NLP/llm2vec/blob/68dc1d3244cc710942a5bbbf11d9677de9f8f68a/train_configs/simcse/MetaLlama3.json#L3) as an initialization point before we begin any simcse training. 

To do "bi+simce", simply remove this line from the configuration. 

Let me know if you have any more queries.

**Comment by vaibhavad** [comment]
Closing as it is stale, let me know if you have any more questions.
