### ISSUE TITLE
Can you please share some examples

### ISSUE THREAD

**Issue by andysingal** [McGill-NLP/llm2vec#2]
Can you please share some examples

**Comment by vaibhavad** [comment]
Hi, thanks for your interest in the work. Our [README](https://github.com/McGill-NLP/llm2vec?tab=readme-ov-file#inference) has an example for document retrieval. Are there any other type of examples you are looking for?

**Comment by monilouise** [comment]
Hi, I'd like to see examples for classification tasks!

**Comment by vaibhavad** [comment]
Hi, we have added more examples in the [examples](https://github.com/McGill-NLP/llm2vec/tree/main/examples) repository. Hope that helps. Feel free to reach out if you have any more queries.
