### ISSUE TITLE
No "unmasked_value" parameter

### ISSUE THREAD

**Issue by JingfenQiao** [McGill-NLP/llm2vec#24]
File ".cache/huggingface/modules/transformers_modules/McGill-NLP/LLM2Vec-Sheared-LLaMA-mntp/813a65a03add82b52fb2664efc85b0a1ed8661d3/attn_mask_utils.py", line 62, in _prepare_4d_attention_mask_for_sdpa
    expanded_4d_mask = AttentionMaskConverter._unmask_unattended(
TypeError: _unmask_unattended() got an unexpected keyword argument 'unmasked_value'

**Comment by fac2003** [comment]
Also seeing this error. Trying on CPU with no cuda for now so I did not install flash attention. Not sure yet if this this related. How did you get past the error?

**Comment by JingfenQiao** [comment]
It may come from the old version of the attn_mask_ultils.py file, it works by replacing it with the following:  expanded_4d_mask = AttentionMaskConverter._unmask_unattended(expanded_4d_mask, min_dtype=torch.finfo(inputs_embeds.dtype).min)

**Comment by JingfenQiao** [comment]
> Also seeing this error. Trying on CPU with no cuda for now so I did not install flash attention. Not sure yet if this this related. How did you get past the error?

It may come from the old version of the attn_mask_ultils.py file, it works by replacing it with the following:  expanded_4d_mask = AttentionMaskConverter._unmask_unattended(
                expanded_4d_mask, min_dtype=torch.finfo(inputs_embeds.dtype).min
            )

**Comment by fac2003** [comment]
Thanks for the details. It would have been best to leave the issue open until this problem was fixed in the latest version installable with pip.

**Comment by vaibhavad** [comment]
Hi @JingfenQiao, which transformer version are you using?

**Comment by vaibhavad** [comment]
Hi @JingfenQiao and @fac2003, thank you for highlighting the issue. @JingfenQiao thanks for proposing a fix. I have updated the HuggingFace repo to incorporate implementation change due to different transformers version. You can check the fix [here](https://huggingface.co/McGill-NLP/LLM2Vec-Sheared-LLaMA-mntp/commit/48b3d3bbbfc63bd39be88fad20a85e5cce4c5b81). Please re-open this issue if you still face this problem.
