### ISSUE TITLE
Question about Finetune Code Release

### ISSUE THREAD

**Issue by rr191211** [McGill-NLP/llm2vec#25]
Awesome research! I'm really impressed by your work. Just wondering, when do you plan to release the finetuning code? Thank you.

**Comment by eun-younglee** [comment]
You can finetune with this code, however it seems it's not working well with Llama right now. 
`python experiments/run_mntp.py train_configs/mntp/Mistral.json`

**Comment by ParishadBehnam** [comment]
Hi,
Thanks for your interest. 
The [training code of MNTP](https://github.com/McGill-NLP/llm2vec?tab=readme-ov-file#mntp-training) has been released. We will release SimCSE and supervised training code soon as well.
