### ISSUE TITLE
`validation_split_percentage` for train split is incorrect?

### ISSUE THREAD

**Issue by MicPie** [McGill-NLP/llm2vec#27]
Hello,
thank you for releasing the code for your great LLM2Vec work!

I think the `validation_split_percentage` for train split `if "validation" not in raw_datasets.keys():` is incorrect, see lines:
https://github.com/McGill-NLP/llm2vec/blob/main/experiments/run_mntp.py#L609
and
https://github.com/McGill-NLP/llm2vec/blob/main/experiments/run_mntp.py#L575
as this (`val%`)
```
split=f"train[{data_args.validation_split_percentage}%:]",
```
needs to be changed to `100% - val% = train%`:
```
split=f"train[{100-data_args.validation_split_percentage}%:]",
```
unless I don't get the code fully.

**Comment by vaibhavad** [comment]
Hello @MicPie,

Thanks for your interest in our work. The implementation seems correct to me. Let's say `validation_split_percentage` is set to 5% (default value), then the first 5% samples are set as validation ([Line 567](https://github.com/McGill-NLP/llm2vec/blob/main/experiments/run_mntp.py#L567)) and next 95% are set as train ([Line 575](https://github.com/McGill-NLP/llm2vec/blob/main/experiments/run_mntp.py#L575)).

The implementation is similar to [HuggingFace  RoBERTa MLM script](https://github.com/huggingface/transformers/blob/51bcadc10a569847b93a30dbe3a077037ae63bad/examples/pytorch/language-modeling/run_mlm.py).

Let me know if you have any more queries.

**Comment by MicPie** [comment]
Hi @vaibhavad , sorry you are right, I should have tested before, sorry for the creating the issue.
