### ISSUE TITLE
No module named 'flash_attn_2_cuda'

### ISSUE THREAD

**Issue by revantteotia** [McGill-NLP/llm2vec#30]
Although I have installed flash attention, I am getting this error

`RuntimeError: Failed to import transformers.models.mistral.modeling_mistral because of the following error (look up to see its traceback):
No module named 'flash_attn_2_cuda'`

**Comment by vaibhavad** [comment]
This seems like an error based on your environment setup. Does this import line work for you?

```python
import flash_attn_2_cuda as flash_attn_cuda
```

**Comment by vaibhavad** [comment]
Closing as it is stale. Please re-open if the problem persists.
