### ISSUE TITLE
Error when reproducing training

### ISSUE THREAD

**Issue by Iambestfeed** [McGill-NLP/llm2vec#33]
Because I want to make some tweaks to test with other models like Qwen, I tried running your repo and I encountered some problems as follows:
![image](https://github.com/McGill-NLP/llm2vec/assets/95571916/4fdb4d5e-1bbc-423f-ac67-dc0b38e2a105)
Train_config:
```python
{
    "model_name_or_path": "princeton-nlp/Sheared-LLaMA-1.3B",
    "dataset_name": "iambestfeed/wiki-text-subset",
    "per_device_train_batch_size": 1,
    "per_device_eval_batch_size": 1,
    "gradient_accumulation_steps": 1,
    "do_train": true,
    "do_eval": true,
    "max_seq_length": 512,
    "mask_token_type": "blank",
    "data_collator_type": "default",
    "mlm_probability": 0.2,
    "overwrite_output_dir": true,
    "output_dir": "output/mlm/Sheared-LLaMA-1.3B",
    "evaluation_strategy": "steps",
    "eval_steps": 100,
    "save_steps": 200,
    "stop_after_n_steps": 1000,
    "lora_r": 16,
    "gradient_checkpointing": true,
    "torch_dtype": "bfloat16",
    "attn_implementation": "flash_attention_2"
}
```
Code: [Colab](https://colab.research.google.com/drive/1azlXeNTbsYhP88lvgFq3Z7D-ecE-4dU6?usp=sharing)
You can go to my notebook shared above and take a look for more clarity. Dataset I created 1 subset from wiki-text to perform for testing.

**Comment by jeonsworld** [comment]
@Iambestfeed Try transformer version==4.39.1

**Comment by vaibhavad** [comment]
@jeonsworld's suggestion is correct. The attention implementation changes based on transformer version. We have followed the latest implementation present in 4.39.1 and above. This requirement is specified in [setup.py](https://github.com/McGill-NLP/llm2vec/blob/f5b6a22d021ccc23ce5c9a7beac7c0ec11d9676c/setup.py#L25)

**Comment by vaibhavad** [comment]
The llm2vec package has now been made compatible with transformers 4.40.0 and 4.40.1. [Here](https://github.com/McGill-NLP/llm2vec/commit/5492ca5849a0dc3a07063eed60f988940d60df98) is the fix.

You can use the latest version from pip (0.1.5) or install from source using the latest code.

**Comment by vaibhavad** [comment]
Feel free to re-open the issue if you still encounter this error
