### ISSUE TITLE
Are any layers shared with the base model

### ISSUE THREAD

**Issue by matbee-eth** [McGill-NLP/llm2vec#34]
I'm curious if there are any shared layers between _(Mistral-7b-instruct)_ Base and _(LLM2Vec-Mistral-7B-Instruct-v2-mntp)_ MNTP-Base model which we could use to keep parts of the models in memory if we're splitting embedding + inference on the same base

I essentially want to train an LLM LoRa on a custom set of data, and train the MTNP LoRa adapter as well. Would be nice to run inferencing + embedding using as much of the same source as possible.

**Comment by vaibhavad** [comment]
As we enable bidirectional connections and train with lora on all layers, unfortunately there is no shared layer between Mistral-7b-instruct and LLM2Vec-Mistral-7B-Instruct-v2-mntp
