### ISSUE TITLE
forced choice between cpu or cuda device

### ISSUE THREAD

**Issue by fac2003** [McGill-NLP/llm2vec#35]
I would like to use LLM2Vec on an apple GPU (see https://pytorch.org/docs/stable/notes/mps.html). Pytorch supports the device 'mps', but the llm2vec code assumes either cuda or cpu for device type:
in llm2vec.py, line 290. 
device = "cuda" if torch.cuda.is_available() else "cpu"

I changed this line to force device='mps' and confirmed that llm2vec works on GPU on a M3 mac laptop (I see GPU utilization and speedup compared to CPU). 

I understand that most users care about CUDA support, but the 'mps' device is handy for testing on a non-cpu device. Would it be possible to add a device argument to the encode method and to use it instead of the hard-coded choice?
This would also support other devices (TPUs etc, see https://pytorch.org/xla/release/2.3/index.html) that pytorch already supports.

**Comment by fac2003** [comment]
I'm happy to submit a PR if the change sounds reasonable (could default to the current behavior if the device argument is None).

**Comment by vaibhavad** [comment]
This sounds very reasonable. Apologies that we missed it. Feel free to submit a PR. :)

**Comment by fac2003** [comment]
Soungs good. See PR at https://github.com/McGill-NLP/llm2vec/pull/39

**Comment by vaibhavad** [comment]
Thanks for your contribution, the latest code will be updated in the pip package with the next release (~1 week)
