### ISSUE TITLE
Error 403 when trying to load Llama 3

### ISSUE THREAD

**Issue by monilouise** [McGill-NLP/llm2vec#36]
Hi, 

I tried the following code:

`model = LLM2Vec.from_pretrained(
    "McGill-NLP/LLM2Vec-Meta-Llama-3-8B-Instruct-mntp",
    peft_model_name_or_path="McGill-NLP/LLM2Vec-Meta-Llama-3-8B-Instruct-mntp-supervised",
    device_map="cuda" if torch.cuda.is_available() else "cpu",
    torch_dtype=torch.bfloat16, trust_remote_code=True
)`

But got the following error message:

`Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
The argument "trust_remote_code" is to be used with Auto classes. It has no effect here and is ignored.
Loading model...
---------------------------------------------------------------------------
HTTPError                                 Traceback (most recent call last)
[/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_errors.py](https://zo1zijc2nvd-496ff2e9c6d22116-0-colab.googleusercontent.com/outputframe.html?vrz=colab_20240429-060206_RC00_629021898#) in hf_raise_for_status(response, endpoint_name)
    303     try:
--> 304         response.raise_for_status()
    305     except HTTPError as e:

16 frames
HTTPError: 403 Client Error: Forbidden for url: https://huggingface.co/meta-llama/Meta-Llama-3-8B-Instruct/resolve/main/config.json

The above exception was the direct cause of the following exception:

GatedRepoError                            Traceback (most recent call last)
GatedRepoError: 403 Client Error. (Request ID: Root=1-66316395-235be3b059c489180202e862;3a6f891e-9986-4d05-a761-8472d9440a81)

Cannot access gated repo for url https://huggingface.co/meta-llama/Meta-Llama-3-8B-Instruct/resolve/main/config.json.
Access to model meta-llama/Meta-Llama-3-8B-Instruct is restricted and you are not in the authorized list. Visit https://huggingface.co/meta-llama/Meta-Llama-3-8B-Instruct to ask for access.

The above exception was the direct cause of the following exception:

OSError                                   Traceback (most recent call last)
[/usr/local/lib/python3.10/dist-packages/transformers/utils/hub.py](https://zo1zijc2nvd-496ff2e9c6d22116-0-colab.googleusercontent.com/outputframe.html?vrz=colab_20240429-060206_RC00_629021898#) in cached_file(path_or_repo_id, filename, cache_dir, force_download, resume_download, proxies, token, revision, local_files_only, subfolder, repo_type, user_agent, _raise_exceptions_for_gated_repo, _raise_exceptions_for_missing_entries, _raise_exceptions_for_connection_errors, _commit_hash, **deprecated_kwargs)
    414         if resolved_file is not None or not _raise_exceptions_for_gated_repo:
    415             return resolved_file
--> 416         raise EnvironmentError(
    417             "You are trying to access a gated repo.\nMake sure to have access to it at "
    418             f"[https://huggingface.co/{path_or_repo_id}.\n{str(e)}](https://huggingface.co/%7Bpath_or_repo_id%7D./n%7Bstr(e)%7D)"

OSError: You are trying to access a gated repo.
Make sure to have access to it at https://huggingface.co/meta-llama/Meta-Llama-3-8B-Instruct.
403 Client Error. (Request ID: Root=1-66316395-235be3b059c489180202e862;3a6f891e-9986-4d05-a761-8472d9440a81)

Cannot access gated repo for url https://huggingface.co/meta-llama/Meta-Llama-3-8B-Instruct/resolve/main/config.json.
Access to model meta-llama/Meta-Llama-3-8B-Instruct is restricted and you are not in the authorized list. Visit https://huggingface.co/meta-llama/Meta-Llama-3-8B-Instruct to ask for access.`

Any ideas?

Thanks!

**Comment by vaibhavad** [comment]
Hi, as the error says, you have to first request access to [Meta-Llama-3-8B-Instruct](https://huggingface.co/meta-llama/Meta-Llama-3-8B-Instruct). Then either do CLI login or provide the huggingface token while using the model

**Comment by monilouise** [comment]
Hi, thanks!  After registering on the site, I receive the following message:

Your request to access this repo has been successfully submitted, and is pending a review from the repo's authors.

Do you happen to know if this process takes too long?

**Comment by monilouise** [comment]
Access granted.
