### ISSUE TITLE
Is "unidirectional' result in Fig. 3 based on the LLM as-is (i.e no any fine-tuning/training)?

### ISSUE THREAD

**Issue by xwk** [McGill-NLP/llm2vec#38]
Nice work! Just want to clarify a confusion I have when reading the Fig. 3 in your paper. Are the results labeled as 'uni' obtained with a off-the-shelf LLM without any finetuning/tranining. If this is the case, this is somewhat unexpected to see an off-the-shelf LLM could achieve such decent result, in paticular with the mean+uni or weighted-mean+unit options.

**Comment by vaibhavad** [comment]
Yes, results labeled as 'uni' obtained with a off-the-shelf LLM without any finetuning/training. LLMs do also keep surprising us :)
