### ISSUE TITLE
Nice work, have you extended this to cross-encoders?

### ISSUE THREAD

**Issue by RayyanRiaz** [McGill-NLP/llm2vec#4]
Dear authors,

First of all, congratulations on this nice work!

I wanted to ask if you have tried extending this to cross-encoders? Asking because cross-encoders are used as re-rankers in RAGs and a good re-ranker is important for overall RAG performance. I think extending the current architecture to cross-encoders would not be very hard, and can really be a ripe, low-hanging fruit.

P.S., I apologize in advance if such work is already done. Really hard to navigate through the research papers these days :D

**Comment by vaibhavad** [comment]
Hi @RayyanRiaz,

Thank you for your interest in our work. We have currently not extended LLM2Vec for cross-encoders. In this work, we mainly considered making strong LLM-based encoders for general sentence representations.

We hope the community will explore the LLM2Vec recipe for more specific tasks such as retrieval and adapt these models for cross-encoders/re-rankers too. In my opinion, a good starting point will be to take [Bi + MNTP](https://huggingface.co/McGill-NLP/LLM2Vec-Mistral-7B-Instruct-v2-mntp) checkpoint of LLM2Vec and then further fine-tune it as a reranker, following the training and evaluation setup as described in this [paper](https://arxiv.org/abs/2310.08319).
