### ISSUE TITLE
Is it possible to train this model for Token classification Task?

### ISSUE THREAD

**Issue by codingchild2424** [McGill-NLP/llm2vec#42]
Great work! Thank you for all of you.

I wonder is it possible to train this model for token classification task?

I saw, in the paper, that the this model can be used to NER task which is variant of token classification task.

**Comment by ParishadBehnam** [comment]
Hi,
Thanks for your interest in our work. 
We recently updated the repository with token classification training and testing codes and running scripts. Please note that in our experiments, we did not train the models weights, and only a one-layer classifier is trained. Please take a look at the code and let us know if you have further questions.

**Comment by vaibhavad** [comment]
Feel free to re-open if you have any further questions
