### ISSUE TITLE
"ModuleNotFoundError: No module named 'transformers.pytorch_utils' when using llm2vec with transformers 4.40.1"

### ISSUE THREAD

**Issue by sdspieg** [McGill-NLP/llm2vec#46]
- Is the module transformers.pytorch_utils expected to exist in transformers version 4.40.1?
- Are there any known compatibility issues with transformers 4.40.1 and llm2vec or peft that I should be aware of?

**Comment by vaibhavad** [comment]
Which version of llm2vec are you using? The latest version of llm2vec is compatible with transformers 4.40.1. Can you share the exact command that resulted in the error?

**Comment by vaibhavad** [comment]
Closing as it is stale. Feel free to re-open if you have any more questions regarding this issue.
