### ISSUE TITLE
Evaluating MNTP task only

### ISSUE THREAD

**Issue by nurlanov-zh** [McGill-NLP/llm2vec#48]
Thanks for your work.

I am wondering if you plan to provide an example script for loading and evaluating the MNTP task only. In my experiments, the results are `_attn_implementation` dependent...

**Comment by vaibhavad** [comment]
> In my experiments, the results are _attn_implementation dependent...

I am not sure what you mean by this. Can you elaborate?

We do not evaluate MNTP task separately as it is not used for either word level or sentence level tasks. In-training evaluation takes place when you [train for MNTP](https://github.com/McGill-NLP/llm2vec?tab=readme-ov-file#mntp-training).

 However it is easy to do MNTP eval with two changes
1. In the [config file](https://github.com/McGill-NLP/llm2vec/blob/c5cb6d7d07d65d4fd1cd2d508896ea0ab4604822/train_configs/mntp/Mistral.json#L8), change `do_train` from `true` to `false`.
2. In [`experiments/run_mntp.py`](https://github.com/McGill-NLP/llm2vec/blob/c5cb6d7d07d65d4fd1cd2d508896ea0ab4604822/experiments/run_mntp.py#L700-L705), change Line 700-705 to
```python
    from peft import PeftModel
    model.model = PeftModel.from_pretrained(
        model.model,
        <HF MNTP MODEL ID>,
    )
```

After these two changes, when you run
```bash
python experiments/run_mntp.py train_configs/mntp/Mistral.json
```
The script will give MNTP evaluation results. For Mistral, I got the following scores
```
***** eval metrics *****
  eval_accuracy           =     0.2474
  eval_loss               =     4.6248
  eval_runtime            = 0:00:11.83
  eval_samples            =        568
  eval_samples_per_second =     47.991
  eval_steps_per_second   =      1.521
  perplexity              =   101.9872
```

**Comment by vaibhavad** [comment]
Feel free to re-open if you have any more questions about this issue.
