### ISSUE TITLE
after training, the model with mmlu performace would downgrade?

### ISSUE THREAD

**Issue by trouble-maker007** [McGill-NLP/llm2vec#49]

**Comment by vaibhavad** [comment]
As the models are trained to be encoders and not be generative, it is very likely the MMLU performance of LLM2Vec models will be lower than their causal LM counterparts.

**Comment by vaibhavad** [comment]
Feel free to re-open if you have any more questions about this issue.

**Comment by trouble-maker007** [comment]
@vaibhavad thanks for the response, I just wonder after llm2vec, llm model a better text encoder than t5 in sd training
