### ISSUE TITLE
Please post SimCSE training code

### ISSUE THREAD

**Issue by dbourget** [McGill-NLP/llm2vec#59]
Hi! This work is super interesting! I would love to try out the SimCSE approach with llama 3. Please post the SimCSE training code discussed in the paper. Thanks!

**Comment by vaibhavad** [comment]
Hi, I am working on SimCSE code in #62. The code is functional but I still need to run some tests before merging it into the main codebase.

**Comment by vaibhavad** [comment]
The code has been released and merged with main :) Feel free to re-open this issue if you have any more questions.
