### ISSUE TITLE
About sample ratio of E5 dataset

### ISSUE THREAD

**Issue by liuqi6777** [McGill-NLP/llm2vec#61]
Hi, I see that you mentioned using different sample ratios for different datasets during supervised training in the paper, but I don't see it in the code. So are you sampling the dataset in advance and then loading the sampled dataset during training? Or is it that some code was missing?

**Comment by vaibhavad** [comment]
Hi, thanks for your interest in our work. We directly got the supervised data post sampling from [authors of Echo Embeddings](https://github.com/jakespringer/echo-embeddings). We did not do any sampling on our end.
