### ISSUE TITLE
Encoding Device 

### ISSUE THREAD

**Issue by sramshetty** [McGill-NLP/llm2vec#65]
Hi, thanks for sharing your work and the great resource!

When I was encoding samples I found that regardless of whether I explicitly set device to "cuda" or not, when calling `encode(...)`, the output embeddings would be on "cpu". I believe this [line](https://github.com/McGill-NLP/llm2vec/blob/72ac29d686a8a5edb7ffa0d7985251cd77bd29bf/llm2vec/llm2vec.py#L409) causes this, since it will always return embeddings on "cpu" rather than the given/default device we would expect.

**Comment by vaibhavad** [comment]
Hi @sramshetty,

Thank you for your interest in our work. This is done intentionally as for large datasets, incrementally storing embedding on GPU can cause OOM problems. Does your use case require the embeddings to be on GPU?

**Comment by sramshetty** [comment]
I see, that makes sense and I was able to work around it to get embeddings on the GPU. Thanks!
