### ISSUE TITLE
Looking forward to your training code 😄 

### ISSUE THREAD

**Issue by cingtiye** [McGill-NLP/llm2vec#8]

**Comment by vaibhavad** [comment]
Thanks for your interest. The [training code of MNTP](https://github.com/McGill-NLP/llm2vec?tab=readme-ov-file#mntp-training) step has been released. We are working to release SimCSE and supervised training code soon too.

**Comment by vaibhavad** [comment]
All the training code and details have been released

https://github.com/McGill-NLP/llm2vec?tab=readme-ov-file#training

**Comment by vaibhavad** [comment]
Fell free to re-open if you have any more questions related to this issue.
