### ISSUE TITLE
some special words can not be encoded

### ISSUE THREAD

**Issue by Yan2266336** [McGill-NLP/llm2vec#80]
I just followed your instructions of code to convert the llama 3-8b-instruct model into an embedded. When I use the l2v.encode() function to get embedding of sentence "Buddhism (religion/philosophy)", the code will raise an issue about "RuntimeError: The expanded size of the tensor (10) must match the existing size (12) at non-singleton dimension 0.  Target sizes: [10].  Tensor sizes: [12]". Just some special words can raise this kind of issues. So do you know the reason of this problem?

**Comment by vaibhavad** [comment]
Hi, can you share a code snippet to reproduce the issue?

**Comment by Yan2266336** [comment]
ok.
Firstly, I converted the foundational llama 3-8b-instruct model into an embedder, named "Llama-3-8B-instruct-Emb".
<img width="364" alt="image" src="https://github.com/McGill-NLP/llm2vec/assets/163033528/edba66ce-7c47-49ce-b0c2-d89daf0a6504">

Then, I follow your instructions to reload this model and use this model to get embedding.
 
<img width="1140" alt="image" src="https://github.com/McGill-NLP/llm2vec/assets/163033528/fcf1473c-732d-4b1e-b9ed-4186fdb75fc2">

In the end, I use "l2v.encode()" to generate embedding.
<img width="962" alt="image" src="https://github.com/McGill-NLP/llm2vec/assets/163033528/c1df287c-8264-49a2-adca-03fa31c6dd60">

It is just an example of this issue. Most sentences can generate embedding correctly, but some sentences will raise this problem. So, I don't know how to solve this issue.

**Comment by vaibhavad** [comment]
Hi @Yan2266336,

I believe you are mixing two different ways of loading the model. The loading using `transformers` and `trust_remote_code` is required for loading Huggingface models, which have custom files that are needed for bidirectional attention. `l2v.save` will not save those files, hence if you load from a local directory, you are actually using a unidirectional model instead of bidirectional.

If you are saving using `l2v.save`, then you should be loading the model with `l2v = LLM2Vec.from_pretrained` method.

This code snippet is working without any errors on my end

```python
import torch
from llm2vec import LLM2Vec

if __name__ == "__main__":
    l2v = LLM2Vec.from_pretrained(
        "meta-llama/Meta-Llama-3-8B-Instruct",
        device_map="cuda",
        torch_dtype=torch.bfloat16,
        low_cpu_mem_usage=True,
    )

    l2v.encode(["Buddhism (religion/philosophy)"])
```

**Comment by Yan2266336** [comment]
Thank you so much for helping me to solve this issue. However, arises another issue when I use this code to get embeddings, just as shown in the figure.

<img width="451" alt="image" src="https://github.com/McGill-NLP/llm2vec/assets/163033528/460b746d-9fb3-4eaa-8681-cccff6dfdc99">
<img width="576" alt="image" src="https://github.com/McGill-NLP/llm2vec/assets/163033528/c47c07d6-2cd4-4d5b-9337-a50f596ab009">
 
Do you know what the problem is? Because I have tried this way to get embeddings, but it didn't work. Therefore, I used the code you shared in the hugging face to get the embeddings.

**Comment by Yan2266336** [comment]
It works. Thanks for helping me to solve these problems.

**Comment by vaibhavad** [comment]
No problem. Feel free to re-open the issue if you have any more questions

**Comment by Yan2266336** [comment]
Hello, I have to bother you again. recently I Instruct-tuned a 'meta-llama/Meta-Llama-3-8B-Instruct' model and pushed it into my hugging face, this model is 'YBXL/Meta-Llama-3-8B-InstUMLS-Concept-train11e-06'. The model's structure is shown here:
<img width="1299" alt="image" src="https://github.com/McGill-NLP/llm2vec/assets/163033528/1d040f51-c2df-4929-b92e-8bf87cfaab9c">

However, I used the same way to load my model into the llm2vec framework, and the previous issue arose again.
<img width="1130" alt="image" src="https://github.com/McGill-NLP/llm2vec/assets/163033528/9c8b44e6-5212-4691-acac-cc441042012d">

<img width="896" alt="image" src="https://github.com/McGill-NLP/llm2vec/assets/163033528/f6ca5527-44f9-43ad-8ca0-55bf4acdd9c2">

<img width="1126" alt="image" src="https://github.com/McGill-NLP/llm2vec/assets/163033528/11445baf-8ea3-492f-b2d5-31e9262fb45c">

I also tested the foundational llama-3-8b-instruct model and my previous fine-tuned llama model, they are still working. only the lasted one "YBXL/Meta-Llama-3-8B-InstUMLS-Concept-train11e-06", the llm2vec arose this problem. Could you please help me to solve this problem? Thank you so much.

**Comment by Yan2266336** [comment]
It seems like there are some issues with responding, I didn't see any of your responses.

**Comment by vaibhavad** [comment]
@Yan2266336, the issue arises because the input text is not put in a proper template. This step happens here, but because the model name has changed, the if condition is not satisfied. Here is a quick workaround to override the function and apply Llama-3 template.

```python
from llm2vec import LLM2Vec

import torch

class CustomModel(LLM2Vec):
    def prepare_for_tokenization(self, text):
        text = (
            "<|start_header_id|>user<|end_header_id|>\n\n"
            + text.strip()
            + "<|eot_id|>"
        )
        return text


l2v = CustomModel.from_pretrained(
    "YBXL/Meta-Llama-3-8B-InstUMLS-Concept-train11e-06",
    device_map="cuda",
    torch_dtype=torch.bfloat16,
    low_cpu_mem_usage=True
    )

l2v.encode(["Buddhism (religion/philosophy)"])
```

**Comment by Yan2266336** [comment]
Thank you so much. So, in the future, I just need to define a custom model as you described here to fit the prompt template, right? Unless you design a prompt template outside the package later on.

**Comment by vaibhavad** [comment]
Yes, exactly. Your understanding is correct.

**Comment by vaibhavad** [comment]
Closing as it is stale. Feel free to re-open if there are any more questions.
