### ISSUE TITLE
Sentence pair classification?

### ISSUE THREAD

**Issue by davedgd** [McGill-NLP/llm2vec#83]
I’ve perused the examples, which are fantastic, but I’m curious: Would it be possible to extend this approach to sentence pair classification?

**Comment by vaibhavad** [comment]
Yes, definitely, in our [paper](https://arxiv.org/abs/2404.05961), we do evaluate on sentence pair classification using the [MTEB benchmark](https://huggingface.co/spaces/mteb/leaderboard). Unfortunately, we don't have an example file for that at the moment. Feel free to start a PR if you are interested in contributing.

**Comment by vaibhavad** [comment]
Looking forward to it :)

Feel free to re-open the issue if you have any more questions
