### ISSUE TITLE
Does the instruction before question have any significance? 

### ISSUE THREAD

**Issue by aldrinjenson** [McGill-NLP/llm2vec#86]
Hi,
I noticed that in the ReadMe example, there are instructions like "Given a web search query, retrieve relevant passages that answer the query:" added to each of the question as a prefix.
I couldn't find any information on this in the paper as to why it is done.

Could you provide the use of doing it this way. Will skipping the instruction or even changing the wording of the instructions affect the result quality of the final embedding?  How significant will it be?

**Comment by vaibhavad** [comment]
Hi @aldrinjenson,

Thanks for your interest in our work.

Instructions are necessary to differentiate between different tasks when using a single model, e.g. - retrieval, classification, sentence similarity etc. We mention the details of our setup in Section 3.2 in the [paper](https://arxiv.org/abs/2404.05961). The list of all instructions used are given in Table 8 and Table 10.

In general, the field of instruction following encoders is a well explored field. The [Instructor](https://arxiv.org/abs/2212.09741) paper has more details about motivation to use instructions for encoding.

Let me know if you have any more questions.

**Comment by aldrinjenson** [comment]
Ahh. This makes sense.
Thanks a lot for the clarification @vaibhavad!
