### ISSUE TITLE
How to get sentence embedding from last hidden state?

### ISSUE THREAD

**Issue by InfAGI** [McGill-NLP/llm2vec#89]
inputs = l2v.tokenizer(doc, return_tensors="pt", padding=True, add_special_tokens=False)
res = l2v.model(**inputs, output_hidden_states=True).last_hidden_state.mean(dim=1)
Is this implementation equivalent to the encode function? Thank you!

**Comment by vaibhavad** [comment]
Closing as it is stale. Feel free to re-open if you have any further questions.

**Comment by andrewdotwang** [comment]
I have a similar question - is it possible to obtain the the sentence embedding as a whole, (embeddings for each token) without any pooling methods?
