### ISSUE TITLE
Usage for multiple Contexts

### ISSUE THREAD

**Issue by harshg99** [McGill-NLP/llm2vec#98]
Hi,
I am trying to run an experiment where we parse multiple contexts receive embeddings for each context, and evaluate how useful each context is for decision-making. Currently, my implementation merges different contexts and receives embedding for each merged context. Eg If I have 3 contexts - c1, c2, c3, I have to merge c1+c2, and c1 +c2 + c3 strings as individual sentences. Is there a way to efficiently merge llm2vec embeddings with a new context or string. For instance, if I have computed the embedding of c1+c2, I only need to evaluate it with c3, to receive the embedding for c1+c2+c3.

**Comment by vaibhavad** [comment]
Closing as it is stale. Feel free to re-open if you have any more questions.
