### ISSUE TITLE
Bypass wandb check

### ISSUE THREAD

**Issue by jeffreyzhang92** [McGill-NLP/llm2vec#99]
Hello,

I need to run the supervised training as a batch job, and as such I will not be able to interact with the script at all once it is running. Is there a way to bypass the wandb check? ie this prompt:

```
wandb: (1) Create a W&B account
wandb: (2) Use an existing W&B account
wandb: (3) Don't visualize my results
wandb: Enter your choice:
```

Thank you!

**Comment by vaibhavad** [comment]
Hi @jeffreyzhang92,

If you provide wandb token as an environment variable, then this check will not be used. If you don't want to use wandb at all, then you should uninstall it from your environment. That will also bypass this check.

Let me know if you have any further questions.

**Comment by vaibhavad** [comment]
Closing as it is stale. Feel free to re-open if you have any more questions.
